language: en-US
tone_instructions: ''
early_access: false
enable_free_tier: true

reviews:
  profile: assertive
  request_changes_workflow: false
  high_level_summary: true
  high_level_summary_placeholder: '@coderabbitai summary'
  high_level_summary_in_walkthrough: false
  auto_title_placeholder: '@coderabbitai'
  auto_title_instructions: ''
  review_status: true
  commit_status: true
  fail_commit_status: false
  collapse_walkthrough: false
  changed_files_summary: true
  sequence_diagrams: true
  assess_linked_issues: true
  related_issues: true
  related_prs: true
  suggested_labels: true
  auto_apply_labels: false
  suggested_reviewers: true
  auto_assign_reviewers: false
  poem: true
  labeling_instructions: []
  # Focus reviews on Go & related project files
  path_filters:
    - "**/*.go"
    - "go.mod"
    - "go.sum"
    - "**/*.proto"
    - "**/*.md"
    - ".golangci.yml"
  path_instructions:
    - path: "CHANGELOG.md"
      instructions: |
        Review the changelog in the PR for spelling mistakes, grammatical errors, and overall clarity. Ensure the language is accessible to non-technical users by flagging overly complex jargon and suggesting simpler alternatives. Check that all changes are properly categorized (like Bug fixes, Features, etc.) and formatted consistently with previous releases. Verify that user-facing changes clearly explain their impact and benefits rather than just technical implementation details. Look for completeness - ensuring significant changes are documented while avoiding trivial internal updates. Suggest improvements for better organization, clearer phrasing, or enhanced user value communication. Focus on making the changelog valuable for all stakeholders, from developers to business users, by maintaining the established format while prioritizing clarity and user impact over technical complexity.
    - path: "**/*_test.go"
      instructions: |
        Treat missing error checks as non-blocking suggestions unless they hide a real failure mode. Prefer clear test setup over boilerplate.
        - It’s acceptable to ignore errors for operations that are effectively infallible in the test context (e.g., UUID generation using well-vetted libs), but suggest `require.NoError(err)` when the failure would meaningfully invalidate the test.
        - Prioritize readability, fixture isolation, and clear failure messages (e.g., testify's `require`/`assert`), over exhaustive error plumbing.
        - Encourage `t.Helper()`, table-driven tests, and descriptive subtest names.
  abort_on_close: true
  disable_cache: false
  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords: []
    labels: []
    drafts: false
    base_branches:
      - develop
      - production
      - ".*" # all branches
  finishing_touches:
    docstrings:
      enabled: true
    unit_tests:
      enabled: true

tools:
  # Keep only tools relevant to a Go repo (you can re-enable others if needed)
  golangci-lint:
    enabled: true
  semgrep:
    enabled: true
  markdownlint:
    enabled: true
  yamllint:
    enabled: true
  actionlint:
    enabled: true
  gitleaks:
    enabled: true
  github-checks:
    enabled: true
    timeout_ms: 90000
  # Disable non-Go linters to reduce noise
  ruff: { enabled: false }
  eslint: { enabled: false }
  biome: { enabled: false }
  swiftlint: { enabled: false }
  phpstan: { enabled: false }
  detekt: { enabled: false }
  rubocop: { enabled: false }
  pmd: { enabled: false }
  cppcheck: { enabled: false }
  clippy: { enabled: false }
  hadolint: { enabled: false }
  sqlfluff: { enabled: false }
  pylint: { enabled: false }
  oxc: { enabled: false }
  shopifyThemeCheck: { enabled: false }
  luacheck: { enabled: false }
  brakeman: { enabled: false }
  dotenvLint: { enabled: false }
  htmlhint: { enabled: false }
  checkmake: { enabled: false }
  buf:
    enabled: true
  regal:
    enabled: true
  circleci:
    enabled: true

chat:
  auto_reply: true
  integrations:
    jira:
      usage: auto
    linear:
      usage: auto

knowledge_base:
  opt_out: false
  web_search:
    enabled: true
  learnings:
    scope: auto
  code_guidelines:
    enabled: true
    file_patterns:
      - "**/CHANGELOG.md"
  issues:
    scope: auto
  jira:
    usage: auto
    project_keys: []
  linear:
    usage: auto
    team_keys: []
  pull_requests:
    scope: auto

code_generation:
  docstrings:
    language: en-US
    path_instructions: []
  unit_tests:
    path_instructions: []
