// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/bmbl-bumble2/recs-votes-storage/config"
	"github.com/bmbl-bumble2/recs-votes-storage/internal/app"
	"github.com/bmbl-bumble2/recs-votes-storage/internal/app/api"
	"github.com/bmbl-bumble2/recs-votes-storage/internal/app/bootstrap"
	"github.com/bmbl-bumble2/recs-votes-storage/internal/context/voting/application"
	"github.com/bmbl-bumble2/recs-votes-storage/internal/context/voting/application/messaging/handler"
	"github.com/bmbl-bumble2/recs-votes-storage/internal/context/voting/application/operation"
	repository2 "github.com/bmbl-bumble2/recs-votes-storage/internal/context/voting/domain/counter/repository"
	"github.com/bmbl-bumble2/recs-votes-storage/internal/context/voting/domain/romance/repository"
	"github.com/bmbl-bumble2/recs-votes-storage/internal/context/voting/infrastructure/persistence"
	"github.com/bmbl-bumble2/recs-votes-storage/internal/context/voting/interface/api/rest/v1"
	"github.com/bmbl-bumble2/recs-votes-storage/internal/shared/platform"
	"github.com/bmbl-bumble2/recs-votes-storage/internal/shared/platform/amazon_sns"
	"github.com/bmbl-bumble2/recs-votes-storage/internal/shared/platform/dynamodb"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeApiWebServer(config2 config.Config) (*app.ApiWebServer, error) {
	logger := platform.NewLogger(config2)
	client := dynamodb.NewDynamoDbClient(config2, logger)
	romancesRepository := persistence.NewRomancesRepository(client, config2, logger)
	countersRepository := persistence.NewCountersRepository(client, config2, logger)
	addUserVoteOperation := operation.NewAddUserVoteOperation(romancesRepository, countersRepository, logger)
	getUserVoteOperation := operation.NewGetUserVoteOperation(romancesRepository)
	deleteUserVoteOperation := operation.NewDeleteUserVoteOperation(romancesRepository, countersRepository, logger)
	changeUserVoteOperation := operation.NewChangeUserVoteOperation(romancesRepository, countersRepository, logger)
	getRomanceOperation := operation.NewGetRomanceOperation(romancesRepository)
	deleteRomanceOperation := operation.NewDeleteRomanceOperation(romancesRepository)
	snsPublisher := amazon_sns.NewSnsPublisher(config2, logger)
	deleteRomancesRequestOperation := operation.NewDeleteRomancesRequestOperation(snsPublisher, logger)
	deleteRomancesOperation := operation.NewDeleteRomancesOperation(romancesRepository, snsPublisher, logger)
	deleteRomancesGroupOperation := operation.NewDeleteRomancesGroupOperation(romancesRepository, logger)
	getLifetimeCountersOperation := operation.NewGetLifetimeCountersOperation(countersRepository)
	getHourlyCountersOperation := operation.NewGetHourlyCountersOperation(countersRepository)
	votingService := application.NewVotingService(addUserVoteOperation, getUserVoteOperation, deleteUserVoteOperation, changeUserVoteOperation, getRomanceOperation, deleteRomanceOperation, deleteRomancesRequestOperation, deleteRomancesOperation, deleteRomancesGroupOperation, getLifetimeCountersOperation, getHourlyCountersOperation)
	votesStorageRoutesRegister := v1.NewVotesStorageRoutesRegister(votingService)
	handlerFactory := api.NewHandlerFactory(votesStorageRoutesRegister)
	apiWebServer := app.NewApiWebServer(handlerFactory, config2, logger)
	return apiWebServer, nil
}

func InitializeMessageProcessor(config2 config.Config) (*app.MessageProcessor, error) {
	logger := platform.NewLogger(config2)
	snsSubscriber := amazon_sns.NewSnsSubscriber(config2, logger)
	client := dynamodb.NewDynamoDbClient(config2, logger)
	romancesRepository := persistence.NewRomancesRepository(client, config2, logger)
	countersRepository := persistence.NewCountersRepository(client, config2, logger)
	addUserVoteOperation := operation.NewAddUserVoteOperation(romancesRepository, countersRepository, logger)
	getUserVoteOperation := operation.NewGetUserVoteOperation(romancesRepository)
	deleteUserVoteOperation := operation.NewDeleteUserVoteOperation(romancesRepository, countersRepository, logger)
	changeUserVoteOperation := operation.NewChangeUserVoteOperation(romancesRepository, countersRepository, logger)
	getRomanceOperation := operation.NewGetRomanceOperation(romancesRepository)
	deleteRomanceOperation := operation.NewDeleteRomanceOperation(romancesRepository)
	snsPublisher := amazon_sns.NewSnsPublisher(config2, logger)
	deleteRomancesRequestOperation := operation.NewDeleteRomancesRequestOperation(snsPublisher, logger)
	deleteRomancesOperation := operation.NewDeleteRomancesOperation(romancesRepository, snsPublisher, logger)
	deleteRomancesGroupOperation := operation.NewDeleteRomancesGroupOperation(romancesRepository, logger)
	getLifetimeCountersOperation := operation.NewGetLifetimeCountersOperation(countersRepository)
	getHourlyCountersOperation := operation.NewGetHourlyCountersOperation(countersRepository)
	votingService := application.NewVotingService(addUserVoteOperation, getUserVoteOperation, deleteUserVoteOperation, changeUserVoteOperation, getRomanceOperation, deleteRomanceOperation, deleteRomancesRequestOperation, deleteRomancesOperation, deleteRomancesGroupOperation, getLifetimeCountersOperation, getHourlyCountersOperation)
	deleteRomancesHandler := handler.NewDeleteRomancesHandler(votingService, logger)
	deleteRomancesGroupHandler := handler.NewDeleteRomancesGroupHandler(votingService, logger)
	topicHandler := bootstrap.NewPreparedTopicHandler(deleteRomancesHandler, deleteRomancesGroupHandler, logger)
	topicListener := app.NewTopicListener(snsSubscriber, topicHandler, logger)
	messageProcessor := app.NewMessageProcessor(topicListener, logger)
	return messageProcessor, nil
}

// wire.go:

var PlatformSet = wire.NewSet(platform.NewLogger)

var ReposSet = wire.NewSet(dynamodb.NewDynamoDbClient, persistence.NewRomancesRepository, persistence.NewCountersRepository, wire.Bind(new(repository.RomancesRepository), new(*persistence.RomancesRepository)), wire.Bind(new(repository2.CountersRepository), new(*persistence.CountersRepository)))

var OperationsSet = wire.NewSet(operation.NewGetRomanceOperation, operation.NewDeleteRomanceOperation, operation.NewGetUserVoteOperation, operation.NewAddUserVoteOperation, operation.NewChangeUserVoteOperation, operation.NewDeleteUserVoteOperation, operation.NewGetLifetimeCountersOperation, operation.NewGetHourlyCountersOperation, operation.NewDeleteRomancesRequestOperation, operation.NewDeleteRomancesOperation, operation.NewDeleteRomancesGroupOperation, application.NewVotingService)
